server:
  port: 8090

spring:
  application:
    name: Spring Boot Admin Web
  boot:
    admin:
      url: http://localhost:${server.port}
  jackson:
    serialization: true
  profiles:
    active: dev

endpoints:
  health:
    sensitive: false

---

spring:
  profiles: dev



---

spring:
  profiles: test


---

spring:
  profiles: production-bx
