server:
  port: 8080

spring:
  application:
    name: swagger-demo
  profiles:
    active: dev

---

spring:
  profiles: dev



---

spring:
  profiles: test


---

spring:
  profiles: production-bx
